### ISSUE TITLE
Markdown link is broken

### ISSUE THREAD

**Issue by Maxim-Mazurok** [denoland/chromium_build#1]
There's a link to `../build_overrides/README.md` in file [README.md, line #23](https://github.com/denoland/chromium_build/blame/master/README.md#L23) of project [denoland/chromium_build](https://github.com/denoland/chromium_build), which refers to the file [deno_third_party/v8/build_overrides](https://github.com/denoland/deno_third_party/tree/master/v8/build_overrides)`/README.md` of project [denoland/deno_third_party](https://github.com/denoland/deno_third_party). The problem is, there's no such file there.
And I was unable to find a README for that `build_overrides` folder, checked a couple of branches with no luck.
So, I'm going to add this [README.md](https://github.com/chromium/chromium/blob/master/build_overrides/README.md) from [chromium](https://github.com/chromium/chromium) repo into the [deno_third_party/v8/build_overrides](https://github.com/denoland/deno_third_party/tree/master/v8/build_overrides) folder to fix the broken link.

**Comment by Maxim-Mazurok** [comment]
This is not resolved, but probably should be closed.

**Comment by piscisaureus** [comment]
This is just a repo where we float patches on chromium's `build` repo.
We're trying to keep the delta with upstream as small as possible -- a broken link in the upstream repo is frankly not important enough to consider.
