### ISSUE TITLE
set_sources_assigment_filter has been removed from the most recent versions of gn

### ISSUE THREAD

**Issue by rhencke** [denoland/chromium_build#4]
[set_sources_assigment_filter has been removed from the most recent versions of gn](https://chromium.googlesource.com/chromium/src/+/master/docs/no_sources_assignment_filter.md).  This currently prevents the build from working when a local, recent copy of gn is specified with GN.

(Upstream chromium removed this as of https://chromium.googlesource.com/chromium/src/+/dfeb1d7edcba9ac807440a850ff32f35d7079035%5E%21/#F0)

**Comment by piscisaureus** [comment]
The `chromium_build` submodule has been synchronized with upstream in https://github.com/denoland/rusty_v8/pull/568.
This means that the next rusty_v8 release will not require gn support for `set_sources_assignment_filter`.
